@startuml
title Dump stations flow

:""GET https://aeronet.gsfc.nasa.gov/aeronet_locations_extended_v3.txt"";
:aeronet_locations CSV; <<output>>
repeat
  :read record; <<input>>
  :record map;
  :GeoParquet geometry; <<output>>
  :store in the Frame;
repeat while (for each record) is (next) not (EOF)

:Produce GeoParquet output; <<output>>
@enduml
